# Generated by Django 2.1.1 on 2018-09-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='body',
            new_name='store_loc',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_dte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_dte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
