# Generated by Django 2.1.1 on 2018-09-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('car_id', models.IntegerField(blank=True, db_column='Car_ID', primary_key=True, serialize=False)),
                ('car_makename', models.CharField(blank=True, db_column='Car_MakeName', max_length=13, null=True)),
                ('car_model', models.CharField(blank=True, db_column='Car_Model', max_length=15, null=True)),
                ('car_series', models.CharField(blank=True, db_column='Car_Series', max_length=35, null=True)),
                ('car_seriesyear', models.CharField(blank=True, db_column='Car_SeriesYear', max_length=4, null=True)),
                ('car_pricenew', models.CharField(blank=True, db_column='Car_PriceNew', max_length=6, null=True)),
                ('car_enginesize', models.CharField(blank=True, db_column='Car_EngineSize', max_length=4, null=True)),
                ('car_fuelsystem', models.CharField(blank=True, db_column='Car_FuelSystem', max_length=18, null=True)),
                ('car_tankcapacity', models.CharField(blank=True, db_column='Car_TankCapacity', max_length=5, null=True)),
                ('car_power', models.CharField(blank=True, db_column='Car_Power', max_length=5, null=True)),
                ('car_seatingcapacity', models.CharField(blank=True, db_column='Car_SeatingCapacity', max_length=2, null=True)),
                ('car_standardtransmission', models.CharField(blank=True, db_column='Car_StandardTransmission', max_length=5, null=True)),
                ('car_bodytype', models.CharField(blank=True, db_column='Car_BodyType', max_length=14, null=True)),
                ('car_drive', models.CharField(blank=True, db_column='Car_Drive', max_length=3, null=True)),
                ('car_wheelbase', models.CharField(blank=True, db_column='Car_Wheelbase', max_length=6, null=True)),
            ],
            options={
                'db_table': 'Rawdata',
            },
        ),
    ]
