# Generated by Django 2.1 on 2018-09-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
